# disabled_rules:             # rule identifiers to exclude from running

opt_in_rules:
  - empty_count
  - file_header
  - force_unwrapping
  - object_literal

disabled_rules:
  - todo

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

function_body_length: 100
line_length: 300

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - i
    - n
    - g

force_try: warning
empty_count: warning

#trailing_whitespace:
#  ignores_empty_lines: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  maya-macos(?:Tests)?(?:-launcher)?
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © 2020 KK\. All rights reserved\.
                    \/\/
                    
